import React from 'react';
import Head from 'next/head';
import HomeComponent from '../components/Home';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>How is the weather now?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>How is the weather now?</h1>
      </main>
      <HomeComponent />

      <footer className={styles.footer}>Made by Macos Roberto Ruginski</footer>
    </div>
  );
}
