import React, { useState } from 'react';
import Head from 'next/head';

// Components
import HomeComponent from '../components/Home';
import Layout from '../components/Layout';

export default function Home() {
  const [data, setData] = useState({
    coord: {
      lon: -49.3786,
      lat: -26.2503,
    },
    weather: [
      {
        id: 804,
        main: 'Clouds',
        description: 'nublado',
        icon: '04n',
      },
    ],
    base: 'stations',
    main: {
      temp: 13.46,
      feels_like: 13.37,
      temp_min: 12.92,
      temp_max: 14.47,
      pressure: 1026,
      humidity: 96,
      sea_level: 1026,
      grnd_level: 927,
    },
    visibility: 10000,
    wind: {
      speed: 1.5,
      deg: 102,
      gust: 4.83,
    },
    clouds: {
      all: 100,
    },
    dt: 1630371422,
    sys: {
      type: 2,
      id: 2019885,
      country: 'BR',
      sunrise: 1630315933,
      sunset: 1630357463,
    },
    timezone: -10800,
    id: 3449350,
    name: 'São Bento do Sul',
    cod: 200,
  });

  return (
    <>
      <Head>
        <title>
          {data.name !== ''
            ? `Como está o tempo em ${data.name}?`
            : 'Como está o tempo na minha cidade?'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <script
          data-ad-client="ca-pub-9954854028991061"
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
        />
      </Head>

      <Layout setData={setData} data={data}>
        <HomeComponent data={data} />
        <footer>Made by Macos Roberto Ruginski</footer>
      </Layout>
    </>
  );
}
